package com.github.gatoartstudios.munecraft.core.enums;

public enum EventType {
    LOAD,
    LOADED,
    ENABLE,
    DISABLE,
    RELOAD,
    DATABASE_READY,
    DATABASE_DISCONNECT,
    DATABASE_RECONNECT,
    DATABASE_UPDATE,
    BOT_READY,
    BOT_DISCONNECT,
    BOT_RECONNECT,
    BOT_UPDATE,
    COMMAND_EXECUTE,
    EXECUTE_SERVER_COMMAND,
    EXECUTE_SERVER_COMMAND_RESULT,
    COMMAND_ERROR,
    PLAYER_JOIN,
    PLAYER_LEAVE,
    PLAYER_KILL,
    PLAYER_DEATH,
    PLAYER_CHAT,
    MESSAGE,
    ALERT,
    LOGGING,
    LOGGING_WARNING,
    LOGGING_ERROR,
    LOGGING_DEBUG,
    LOGGING_SUCCESS;

}
