name: ${name}
version: ${version}
main: com.github.gatoartstudios.munecraft.Munecraft
api-version: '1.21'
authors:
  - gatoartstudio
folia-supported: true
load: STARTUP
commands:
  development:
    description: 'Starts the server in development mode'
    usage: '/development <subcommand>'
    aliases:
      - dev
    permission: munecraft.development