name: ${name}
version: ${version}
main: com.github.gatoartstudios.munecraft.Munecraft
api-version: '1.21'
authors:
  - gatoartstudio
folia-supported: true
load: STARTUP

commands:
  development:
    description: 'Starts the server in development mode'
    usage: '/development <subcommand>'
    aliases:
      - dev
    permission: munecraft.development
  staff:
    description: "Toggles staff mode"
    usage: '/staff'
    permission: munecraft.staff
  staffchat:
    description: "Toggles staff chat"
    usage: '/staffchat'
    permission: munecraft.staffchat
  login:
    description: "Logs the player in"
    usage: '/login'
  trash:
    description: "Opens the trash"
    usage: '/trash <arg>'
    permission: munecraft.trash

permissions:
  munecraft.staff:
    description: Permits access to staff commands
    default: op
  munecraft.staff.op:
    description: Allow access to have op when using the staff command
    default: op
  munecraft.staffchat:
    description: Allows access to staff chat
    default: op
  munecraft.development:
    description: Allows access to development commands
    default: op
  munecraft.grave.saveinventory:
    description: Allows saving inventory on death
    default: true
  munecraft.grave.respawnhere:
    description: Allows respawning at the death location
    default: false
  munecraft.grave.public:
    description: Allows making graves public
    default: true
  munecraft.grave.duration:
    description: Allows setting the duration of graves
    default: true
  munecraft.trash:
    description: Allows using the trash
    default: true
  munecraft.trash.hand:
    description: Allows using the trash with the hand
    default: true
  munecraft.trash.menu:
    description: Allows using the trash menu
    default: false
  munecraft.grave.duration.1:
    description: Sets grave duration to 1 hour
    default: true
  munecraft.grave.duration.2:
    description: Sets grave duration to 2 hours
    default: true
  munecraft.grave.duration.3:
    description: Sets grave duration to 3 hours
    default: true
  munecraft.grave.duration.4:
    description: Sets grave duration to 4 hours
    default: true
  munecraft.grave.duration.5:
    description: Sets grave duration to 5 hours
    default: true
